name: Build

on:
  push:

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Set up Haxe
      run: |
        brew install haxe
        export HAXE_STD_PATH="/opt/homebrew/lib/haxe/std"
        haxelib setup ${{ github.workspace }}/haxelib
        haxelib install lime
        haxelib install openfl
        haxelib install feathersui
        haxelib run openfl setup
    - name: Generate Project
      continue-on-error: true
      run: |
        haxelib run openfl build ios
    - name: Build Project
      run: |
        cd bin/ios
        xcodebuild -exportArchive -configuration Release PLATFORM_NAME=iphoneos SDKROOT=iphoneos18.1 -project Minecraft2D.xcodeproj -allowProvisioningUpdates -allowProvisioningDeviceRegistration -DCODE_SIGNING_ALLOWED=NO build -exportOptionsPlist Minecraft2D/exportOptions-development.plist -archivePath Minecraft2D.xcarchive
    
    - name: Create archive
      run: zip -r app.zip .

    - name: Upload to artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: app.zip