name: Build

on:
  push:

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Haxe
      run: |
        brew install haxe
        haxelib install lime
        haxelib install openfl
        haxelib install feathersui
    - name: Build Project
      run: |
        haxelib run openfl test ios
    
    - name: Create archive
      run: zip -r app.zip .

    - name: Upload to artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: app.zip